cloudinary-image-management-and-manipulation-in-the-cloud-cdn/js/cloudinary.js

fixed "tinyMCE is not defined" JS error when TinyMCE is not loaded:
Uncaught ReferenceError: tinyMCE is not defined
at insert_into_post (cloudinary.js?cv=1.1.6&ver=4.5.12:54)
at Object.onMessage (cloudinary.js?cv=1.1.6&ver=4.5.12:102)
at Object.incoming (easyXDM.min.js?ver=4.5.12:24)
at ab (easyXDM.min.js?ver=4.5.12:24)

fixed "tinyMCE is not defined" JS error when TinyMCE is not loaded

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/cloudinary.php

If wp_remote_get fails, it will not return a response array but instead an instance of WP_Error. So checking the response as an array results in a fatal error.

Adds condition for WP_Error, prevents fatal error

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/js/cloudinary.js

When a user resizes the window `update_window_dimensions` would lock the height of `#wpbody` regardless of whether the Cloudinary modal is open or not, preventing scrolling and accessing elements below the main content editor. Putting in a check to make sure the modal is open before applying the height and overflow styles.
Also fixing the Cloudinary Upload/Insert button [not working on ACF fields](https://support.cloudinary.com/hc/en-us/community/posts/360022597432-Cloudinary-Upload-Insert-Button-in-Wordpress-Plugin?page=1#community_comment_360002325492)

Fix update_window_dimensions to fire only when library is visible

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/ui-definitions/tabs/dashboard-content.php

As requested, this now points to:
https://cloudinary.com/documentation/wordpress_integration

Change the 'Learn more' link href

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-settings-page.php

1. `wp core update --version=4.9.12 --force`
2. Switch to PHP `7.3` if you can
3. Go to /wp-admin/admin.php?page=cld_global_transformation&tab=global_video_transformations
4. Expected: The settings appear
5. Actual: there's a PHP error:
>Recoverable fatal error: Object of class Closure could not be converted to string in /Users/ryankienstra/Projects/sites/sitio/wp-includes/formatting.php on line 1045
This error is from:
https://github.com/cloudinary/cloudinary_wordpress/blob/9b10a9815b924fb64a6eebd1d8f8db6de2bd35a1/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-settings-page.php#L415
One of the values that is passed to `sanitize_text_field()` is:
`sanitize_text_field` passes that to `_sanitize_text_fields()`. That's not a problem in WP 5.0+, I think. It [now …

Prevent an error in WP 4.9.12 from field sanitization

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-video.php

After a lot of research on this bug and a lot of failed attempts, I'm finally happy with my solution. 
As Ryan has described, steps to reproduce:
- In /wp-admin > Cloudinary > Global Transformations > Video Settings, select ‘Cloudinary Player'
- Enter h100,w100 as the ‘Video Transformation String’
- Click ‘Save Settings’
- Create a new post in the block editor
- Add a video block
- Click ‘Media Library’
- Select a video that has been synced with Cloudinary, or upload a video and ensure it’s synced
- Click ‘Select'
- Click ‘Preview’ to see the front-end
- Expected: because there’s a global transformation of h100,w100, the video should be 100 x 100
- Actual: the video is its normal size
The Cloudinary video player JS library has a ton of options that can be added when instantiating it …

Cloudinary video player does not conform to transformation string set in the settings

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-video.php

This screenshot demonstrates the bug best:
After bug fix:
There was a hardcoded 300px width being set on the `<video>` element. I override that width on runtime and replace it with 100% instead.

Fixes bug that causes Cloudinary videos to appear cut

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-video.php

Ensure 100% width for videos.

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php

This will allow applying the default transformations when calling the_post_thumbnail().

Add breakpoint flag to convert_url()

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-push-sync.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-queue.php

This PR introduces 2 changes.
First, it delays the resume of the queue to the shutdown.
Secondly, it falls back to cron job to ensure that the queue resumes.

Force stalled queues to resume

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-delete-sync.php

This PR fixes the described issue on CLOUD 409 and it can be replicated by firing both Bulk Sync media and Auto-Sync or manual push to Cloudinary.
Please refer to the ticket to get more details.

Fix a if condition that could stop a listing page

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-video.php

Fixes bug where toggling overwrite transformations for a video didn't really affect the outcome on the page and global transformations were being applied regardless.
Steps to test:
* Add some video global transformations
* Enable "overwrite transformations" on a video in a post
* Observe the post - With this fix, the transformations should not be applied.

Add overwrite_transformations check for global transformations

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-push-sync.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-sync.php

A public ID cannot start with a forward slash.
If the folder is set to none, it defaults to `/` Previously, this was not an issue since we didn't build the folder/public_id structure dynamically. But now, since it is, a root folder asset will start with `/`. i.e `/public-id-jpg`
This fix simply applies a `ltrim( $public_id, '/' )` when combining the folder and id.
An additional fix is that if `auto-upload` is disabled, assets that go out of sync, (changing the folder, or cloudname, etc...) it will show as unsynced. This is because there is a check to see if auto sync is on before uploading. I've added a check to see if it's off unless it's been synced before. if it has, it enables it for just that asset.

ltrim forward slashes on public ID

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-upgrade.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-push-sync.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-sync.php

This is to better handle upgrading from v1 - v2+
@pereirinha - The change in `cloudinary_id` filter came into a requirement here, as this allows us to identify upgrade items and act on them without overly filtering.

add upgrade handling

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-filter.php

I tested this for potential side effects, but I can't see any case where removing slashes is necessary here.
@DavidCramer Could I be missing something here?

Remove unslash when editing in Gutenberg

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-settings-page.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-sync.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-sync.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/ui-definitions/tabs/sync-media-content.php

The syncing status should only be available if the auto-sync feature is enabled.

Fix syncing status

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-sync.php

@pereirinha - the metadata on whats saved (pending, syncing etc) may be outdated. If there is no sync-type needed due to the signature being in sync and up to date, don't show meta data notices, since it's no longer relevant.

add check that a synctype is still available

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-sync.php

allow some sync types to continue rendering cloudinary urls on non required sync types. Like metadata updates etc..

required sync type flag

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php

As described, this ticket will ensure that images that had a `-1` (or `-n`) appended by WP in order to avoid duplicate file names - will still have the `srcset` attribute applied to them.
Test instructions:
- Create a new post and add an image via the Cloudinary tab
- Add another image block
- Select the same image from the Cloudinary tab, but this time add some transformations to this image
- Save the post and observe that all the images will have `srcset` set in the frontend

Add missing srcset to mismatched images

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-filter.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-storage.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-sync.php

If Cloudinary is the single storage source, images inserted in content will try to have Cloudinary URL's filtered into local URLs for saving.
Since these don't exist anymore, we get a broken link in the DB. This is only noticeable if the plugin is disabled though, since the URL's are filtered out while the plugin is active.
Migrating back to WordPress and Cloudinary, also resolves this as it is then able to locate the files.

Broken links on content created while Cloudinary is single source.

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-sync.php

use `Media::cloudinary_id()` method to get file path, name, suffix, and extension.

Correctly match the the file_location and cloudinary_id

---

cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/connect/class-api.php
cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-sync.php

Allows pushing an asset update — either via `Re-sync to Cloudinary` or the bulk action `Push to Cloudinary` — that resets the location of the asset in Cloudinary account to the folder set in WordPress.

Reset folder

---

php/sync/class-push-sync.php

@dugajean @pereirinha f7c088bf5f4f1474d9846019b8e392bdef2b4625 intruduced a infinate loop by moving variable assignment outside of a while loop.
The first has a loop kickout, but causes the sync to work singularly, severely slowing the sync down.
The second was a full infinite loop and would lock up.

fix infinate loop

---

php/class-connect.php
php/settings/class-setting.php
php/ui/component/class-switch-cloud.php

A defect in over-registering settings resulting in a `null` component when requested, which made the `get_url` method to return null. Hence the URL being the same as the current page.
The result is to check that the setting hasn't already been set first.
Additionally, removed the direct calling to the `cloudinary_url` setting by name as well, as the the direct calling of `connect` setting. This would be a technical debt if the settings pages got moved around.
Instead, we use the primary URL setting key as a constant and fetch the settings option parent. 
This will always return the setting page, where the `get_url` will point to wherever the setting is located.

get get_url defect

---

php/class-media.php
php/sync/class-upload-sync.php

- Ensures that `public_id` keeps the suffix on duplicated items;
- Allows forcing upload the asset;

Keep the public_id updated with suffix

---

phpcs.xml.dist

- Comment out the `testVersion` property. This doesn't do anything until the `PHPCompatibilityWP` ruleset is pulled in via Composer and added to this PHPCS config.
- Use the PHPCS 3+ format for array value (text domain). The old format is deprecated and scheduled for removal in PHPCS 4.
- Remove `WordPressVIPMinimum` ruleset, as only `WordPress-VIP-Go` should be used. `WordPress-VIP-Go` builds on top of the old `WordPressVIPMinimum` and updates some violation types, severity, and message, so manually including `WordPressVIPMinimum` again was likely undoing those changes.

PHPCS config improvements

---

php/class-delivery.php
php/class-media.php

Fixes transformations on default breakpoint
- Add an image that includes transformations via the `cld_params` and disable responsive images and well as the lazy load.

Include the `cld_param` transformations on default breakpoints

---

php/media/class-video.php

Fixes the Cloudinary URL for `cname` accounts when using the Cloudinary video player.
- Set the Cloudinary video player, and publish a post with a video. The URL inside the iframe should respect the set cname.

The `secure_distribution` is a required argument when `cname` is set.

---

php/class-media.php

On new imports, the ALT isn't being added as proper meta. Instead, it goes as Cloudinary meta.
- On Cloudinary DAM, choose an image containing caption and alt text that WordPress doesn't yet manage;
- Import that image into WordPress;
- The newly imported image should bring the caption and alt text as expected.

Alt text does not belong to Cloudinary meta

---

php/class-assets.php

Fixes an issue that loses the setting point if the slug has a dot present.

disallow dots in file name

---

php/class-delivery.php
php/class-media.php
php/class-relate.php

When the Cloudinary sync folder contains spaces in its name, the filter out of Cloudinary URLs fails to detect the full URL for the image, corrupting the data stored in the DB.

Support spaces folder name

---

package-lock.json

Reverts cloudinary/cloudinary_wordpress#831

Revert "Bump loader-utils from 1.4.0 to 1.4.2"

---

php/class-media.php

Add a couple of hooks useful when downloading assets from Cloudinary.

Feature hooks download asset

---

php/class-plugin.php

PHP has deprecated dynamically created properties, and it's now throwing a warning.

Declare variable

---

composer.json
composer.lock
php/cache/class-cache-point.php
php/class-assets.php
php/class-media.php
php/class-plugin.php
php/class-report.php
php/class-string-replace.php
php/class-utils.php
php/connect/class-api.php
php/media/class-filter.php
php/media/class-gallery.php
php/media/class-video.php
php/relate/class-relationship.php
php/sync/class-download-sync.php
php/sync/class-sync-queue.php
php/traits/trait-cli.php
php/ui/component/class-info-box.php
php/ui/component/class-notice.php
php/ui/component/class-table.php
phpcs.xml.dist
ui-definitions/components/wizard.php
ui-definitions/settings-image.php
ui-definitions/settings-pages.php
ui-definitions/settings-video.php

This PR addresses some warnings seen on WPVIP.
Aside from minor spacing fixes and alike, it also introduces the following:
- `Utils::attachment_url_to_postid` — a wrapper for `wpcom_vip_attachment_url_to_postid` or use `wp_cache` to store this information. This should have a positive impact on performance;
- fixes on `export_csv` for the CLI commands, which due to the VIP filesystem, could result in an impossibility of storing the export data;
- Increases the sensibility of the PHPCS so that we can sooner spot these issues;

Fix WPVIP feedback

---

php/class-utils.php

I've found another case of potentially running the `md5()` on `null`. Also, there's no point in running the query if there are not URLs to be queried.

If there are no URLs to be processed, no need for the query

---

php/class-utils.php

Fixes the removal of unnecessary fragments.
- Fixes the closing of the file stream;
- Fixes the function to delete the file from the file system
- Download an asset from Cloudinary DAM into WordPress;
- Visit the temp folder — usually `/var/tmp/` or `/tmp/`;
- Confirm that there isn't a file with the following pattern:
- Original filename: `image.jpg`;
- Temporary file: `image-XsWqIe.tmp` — filename suffixed with 6 random chars and the file extension tmp.

Fix closing the filestream and deleting the fragment

---

php/class-delivery.php

- By prepending the base URL with Cloudinary's query argument in the search alias array, we'll ensure that it will try first to replace the URLs where this argument is part of the existing URL.

Prevent the duplication of Cloudinary's analytics query arg

---

php/class-utils.php

If `$thing` only contains a `space` it will generate a php warning when doing `ltrim( $thing )[0]`. This fixes the issue while still being compatible with php 5.4+.
Fixes issue #933

fix: prevent php warning in looks_like_json function

---

php/traits/trait-params.php

- Prevents fatal error when there's corrupted data

Discard faulty params

---

php/class-delivery.php
php/class-plugin.php

Addresses the changes introduced on [WP 6.7](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/) related to the i18n improvements.

Fix plugin loading

---

php/class-utils.php

Starting with PHP 8.0, `$haystack` needs to be a string. Implicit conversion is deprecated.

Fix: Deprecation notices in `Utils::is_rest_api`

---

php/delivery/class-responsive-breakpoints.php

Right now the following set up would not create the smallest image (440px).
This PR updates a condition that prevented the smallest image from being created.

Fix: Responsive breakpoints

---

php/class-delivery.php

This ~~tweaks what is included in the `img` tags on delivery~~ skips completely the filters and transforms on the original tag so the post and pattern editors and pattern list page don't have block editor validation errors.
This is a proof of concept and needs thorough testing.

Block patterns editor issue

---

.gitignore
package-lock.json
php/media/class-gallery.php

Must be enabled by hooking into a filter in code.
```php
add_filter( 'cloudinary_allow_glb_upload', '__return_true' );
```

Experimental support for GLB models.

---

php/class-assets.php

Improving the update asset paths functionality to deliver better performance on the front-end and when performing WP Rest API requests.
- The update and activate asset paths logic was split into two separate methods.
- The process of updating the asset parent paths happens in these cases:
- In the WordPress dashboard and the request is not REST API.
- Using a cron (once a day). This covers manually uploaded plugins/themes.
- The update process happens before the active one to ensure the activated asset parents are up to date.
- Ensure you have the WP Query Monitor plugin installed. 
- Ensure the `Enable additional asset syncing` setting is enabled and there are some plugins/themes activated. (screenshot attached below)
- Go to the WordPress dashboard, and in the WP Query Monitor, filter …

Improve the update asset parent paths functionality for better performance

---

php/class-plugin.php

Changed the version of the video player.
- Ensure the new Cloudinary player renders correctly on the front-end.
- Ensure there are no console warnings from the player.

Change the version of the video player to 2.3.5

---

php/class-delivery.php

Some Page Builders use HTML markup inside JSON, which causes issues with single/double quotes when building our img tag.
- Depending on the provided HTML tag, we use single or double quotes for our HTML element.
- Force the HTML tag to include single quotes (you can mock this locally).
- Do the same for double quotes to ensure it works.

Ensure single and double quotes are properly used when buiding img tags.

---

php/class-delivery.php

The way our plugin uses the `rest_request_before_callbacks` hook causes issues with Rest API requests validation.
- We now use a filter instead of an action.
- We ensure the `$response` is passed when using the `rest_request_before_callbacks` filter.
1. Add the below test filter to a plugin.
2. Go to `/wp-json/wp/v2/media/`.
3. The WP Error should appear. Previously, it was skipped. 
Test filter:
```
add_filter( 'rest_request_before_callbacks', function( $response, $handler, $request) {
return new \WP_Error( 'error', __( 'Force an error to test the filter', "my_textdomain" ) );
}, 7, 3 );
```

Convert maybe_unset_attributes to filter

---

php/sync/class-storage.php

The `size_sync` method of the storage component is used by other components. For example, when preparing a report, the report might use the `size_sync` method, which uses other components.  If the storage isn't `setup`, this leads to a PHP fatal error. 
- Init the setup if `$this->media` is missing
Two options:
- Use `$this->plugin->get_component( 'storage' )->size_sync( $media_id );`  outside of the Storage component.
- Find an attachment without `local_size` or `remote_size`, and generate a report. Previously, it caused errors.

Ensure the storage is setup when using the size_sync outside of the class

---

php/class-media.php
php/class-meta-box.php

- Prepared `init` method for `class-media.php` and `class-meta-box.php`.
- Execute the i18n functions inside the new init methods.
- Ensure there are no PHP warnings.

Correct _load_textdomain_just_in_time PHP warnings

---

php/class-media.php

Fixes https://github.com/cloudinary/cloudinary_wordpress/issues/941
- Avoid warnings when with and height are missing (both main and full sizes).
- Insert an attachment without width or height
- There shouldn't be errors.

Optimize wp_image_matches_ratio in get_crop

---

php/class-meta-box.php

Optimize the execution of `register_handlers` in `class-meta-box.php` for meta hooks loading consistency.

Move register_handlers to init  in class-meta-box.php

---

php/relate/class-relationship.php

Fixes #1049
This adds a magic [`__isset()`](https://www.php.net/manual/en/language.oop5.overloading.php#object.isset) method to the `Cloudinary\Relate\Relationship` class to complement the existing `__get()` and `__set()` methods.
Without this, calling `isset()` on an overloaded property like `public_id` returns `false`, even when it is in fact set.
Following the reproduction steps in the linked issue, calling `isset()` on an overloaded property of a `Relationship` instance should now return `true` if it has a value in the `$data_cache`.

Add `__isset()` method to `Relationship` class

---

php/class-cron.php

Ensuring the cron jobs are enabled by default.
- Adding the name of the cron jobs to the default tasks array.
1. Firstly, add this filter to your local instance (usually this is done as a mu-plugin):
```
/**
* Enables Cloudinary Cron Manager.
* @see http://site.local/wp-admin/admin.php?page=cloudinary&section=cron_system
*/
add_filter( 'cloudinary_feature_cron_manager', '__return_true' );
```
2. After that, go to `wp-admin/admin.php?page=cloudinary&section=cron_system` .
3. Wait for the next run.
4. The last run column should indicate when the last run was. Previously, it said `waiting for`.

Set default cron tasks

---

php/class-delivery.php

Issue: #1022 
Implemented apply_filters in setup_hooks
Simple hooks and implemented in test environment.

add ability to remove dns-prefetch or preconnect link tags

---

php/class-plugin.php

Ensure print_script_data doesn't throw errors when using https://wpcerber.com/how-to-rename-wp-login-php/
- Ensure `$handles = $this->settings->get_param( '@script' );` is executed only when settings are available.
- Install https://wpcerber.com/installation/
- Activate the hidden login page: https://wpcerber.com/how-to-rename-wp-login-php/
- Ensure this error doesn't appear:

Fix WP Ceber login page

---

php/class-delivery.php

Fixes audio source tags.
- Ensuring audio source tags aren't converted.
- Go to a post and insert an audio file.
- The audio file should work correctly on the front-end.
- Install the classic editor.
- Go to a new page and insert an audio file.
- The audio file should work correctly on the front-end.
- There shouldn't be any errors.

Fix audio source tags

---

php/class-svg.php

When we pull an SVG from Cloudinary, if SVG support is enabled we should expect it to be disabled as an SVG file. 
However, it is currently displaying as a PNG.
- If the setting is supported, disable SVG conversion using the `cloudinary_convert_media_types` filter
-  Go to Cloudinary Image Settings page
- Make sure **SVG Support** toggle is enabled
- Create a new post/page
- Add an image block
- Import an SVG from Cloudinary (if none are present in your account, import one using Cloudinary DAM)
- Make sure the SVG is displayed as an SVG on the editor
- Publish and view the post 
- Check that it displays as an SVG on the frontend too and that it has expected SVG transformations (e.g. `f_svg,q_auto/fl_sanitize`)
- Go back to Cloudinary Image Settings page
- Toggle OFF the **SVG Support** …

Avoid SVG conversion for pulled SVG from Cloudinary if SVG support is enabled

---

php/class-sync.php

This ensures that even if the sync types aren't loaded, there's no fatal errors due to sync_types being null.
Main reason: Current fatal errors occurs because the `sync_types` property is set to null (instead of an array). By default, properties in PHP are initialized as null unless told otherwise. By initializing it to an empty array, we can guarantee these fatal errors won't occur.
More detailed investigation of the reported issue:
- This `sync_types` property is assigned only in one place, which is the `setup_sync_types` method, which comes originally from this `init` filter with a priority of **200** https://github.com/cloudinary/cloudinary_wordpress/blob/master/php/class-plugin.php#L278 
- The reported broken site is using another plugin called [Rank Math …

Avoid Sync Types Fatal Errors
