cloudinary/cloudinary_wordpress

- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/cloudinary.php
Fix `build_resize_url` handling of `full` and unsupported size strings
Declare variables that might be used before declaration
Add validation of undefined variables
Comment out unreached code
Improve code readability
> Fix PHP errors( notices) in DEBUG mode

- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/cloudinary.php
Removed the problematic filter.
There's no need to add another `add_filter` as suggested in the issue #3.
> fix button compatibility

- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/sync/class-upload-sync.php
Clears the metadata that marks it as synced, then pushes to Cloudinary.
> allow for a re-sync

- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/css/src/components/_settings.scss
- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/ui-definitions/tabs/settings-global-transformations.php
- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/ui-definitions/tabs/settings-global-video-transformations.php
Demo:
- https://d.pr/i/buCH6C
- https://d.pr/i/FZWcQ4
> Transformations cost warning

- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-sync.php
- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/media/class-upgrade.php
I've found an outstanding issue, in which both keys were being added.
> Avoid key collision

- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
Reverts cloudinary/cloudinary_wordpress#216
> Revert "add format to sync key to make it unique."

- cloudinary-image-management-and-manipulation-in-the-cloud-cdn/php/class-media.php
If the format is set in a transformation, import to WordPress using that format.
> Import using format set in transformation

- php/class-connect.php
- php/connect/class-api.php
Increase time for status cron set usage with data, add referer
> Slow down API calls, and add referer

- css/cloudinary.css
- css/gallery-block-rtl.css
- css/gallery-block.css
- css/src/components/_ui.scss
- css/video.css
- js/block-editor.asset.php
- js/block-editor.js
- js/cloudinary.js
- js/deactivate.asset.php
- js/deactivate.js
- js/gallery-block.asset.php
- js/gallery-block.css
- js/gallery-block.js
- js/gallery-init.asset.php
- js/gallery-init.js
- js/src/components/ui.js
- js/video-init.asset.php
- js/video-init.js
- js/video.js
- package-lock.json
- php/class-sync.php
- php/sync/class-storage.php
- php/ui/component/class-page.php
- ui-definitions/settings-image.php
- ui-definitions/settings-video.php
> Show styled notices instead of default notices

- php/media/class-global-transformations.php
- php/templates/taxonomy-term-transformation-fields.php
- php/templates/taxonomy-transformation-fields.php
Corrects the setting of the `image_freeform` value outside of the terms context.
> Fix taxonomy transformations

- php/class-plugin.php
Improve how assets are enqueued to allow other instances of media modal to get cloudinary tab hooked-in.
> restructure asset enqueuing

- package.json
Prevent being suggested to change on release.
> Versions are supposed to be set by .version

- php/class-delivery.php
- php/class-settings.php
improve sync detection with a signature based on the settings that would cause a sync to happen.
> frontend sync check

- php/class-delivery.php
- php/delivery/class-lazy-load.php
> move urls to after the tags, append CLDBind

- php/class-delivery.php
- php/media/class-filter.php
- Add support for backslashed URLs
- Fixes an issue with the rest requests
> Fix backslashed replacements

- php/delivery/class-lazy-load.php
- php/ui/component/class-lazyload-preview.php
Removes remaining schema on SVGs
> Remove schema on inline SVG

- php/class-delivery.php
- php/class-string-replace.php
- php/class-utils.php
This addresses a few issues identified while delivering complex WPGraphQL queries
> Fix complex objects

- php/media/class-gallery.php
check for `get_current_screen` before trying to use it.
> Check get_current_screen exists

- php/class-connect.php
- php/connect/class-api.php
Allows specifying the region via the `upload_prefix` argument from the connection string
> Support `upload_prefix`

- php/media/class-gallery.php
- src/js/gallery-block/utils.js
> Regex and do_action

- php/class-string-replace.php
Move filtering the result of an api request to pre echo. (exclude internal requests)
> filter result of REST request

- composer.json
- composer.lock
- phpcs.xml.dist
Addresses https://github.com/cloudinary/cloudinary_wordpress/issues/791
> Fix phpcs config file

- php/assets/class-rest-assets.php
- php/class-admin.php
- php/class-assets.php
- php/class-cache.php
- php/class-connect.php
- php/class-deactivation.php
- php/class-delivery.php
- php/class-extensions.php
- php/class-media-library.php
- php/class-plugin.php
- php/class-report.php
- php/class-rest-api.php
- php/class-utils.php
- php/media/class-gallery.php
- php/media/class-global-transformations.php
- php/sync/class-download-sync.php
- php/sync/class-push-sync.php
- php/sync/class-upload-sync.php
Puts all user permissions checks behind a Cloudinary filter
> Make use of `Utils::user_can()`

- php/class-assets.php
Register assets that we can't read their sizes like SVGs in the relationship table without warnings.
> Fix unsizable media

- php/class-delivery.php
- php/class-media.php
Fixes the replacement of Cloudinary URLs for fetched images.
> Fix filter out fetch images

- php/class-connect.php
This PR limits the history for the last 30 days and allows us to store it by plan.
> Improve history

- php/class-media.php
- php/relate/class-relationship.php
Update the alt text and description when pulling from Cloudinary for all the instances.
> Update the alt text and description for all instances of the same image

- php/class-media.php
- php/ui/component/class-crops.php
- php/url/class-cloudinary.php
- ui-definitions/settings-image.php
@DavidCramer 
Here are a set of minor fixes.
> Improvements on url parse crops

- php/class-assets.php
- php/class-delivery.php
- php/class-media.php
- readme.txt
To address:
- static assets from wp-content folders;
- static assets from core folders;
- include testing for encoded URLs
> Feature domain agnostic

- php/class-assets.php
- php/class-delivery.php
- php/class-media.php
- php/class-utils.php
- php/media/class-filter.php
- php/sync/class-storage.php
- php/sync/class-upload-sync.php
Fixes a regression on the agnostic domain feature.
> Hotfix 3.1.6 build 1

- php/connect/class-api.php
Multiplies the timeout based on how many inline transformations are added. This will account for the additional eagers, which takes time.
> add additional timeout for each inline transformation

- php/class-assets.php
- php/class-delivery.php
- php/class-plugin.php
- php/class-report.php
- php/class-utils.php
- php/connect/class-api.php
- php/integrations/class-integrations.php
- php/integrations/class-wpml.php
- php/relate/class-relationship.php
> Feature WPML support

- php/media/class-global-transformations.php
- php/templates/taxonomy-term-transformation-fields.php
- ui-definitions/settings-image.php
- ui-definitions/settings-video.php
There are features where it isn't clear that they are Cloudinary's.
The PR adds that extra context.
> Update wording so it is clear it is a Cloudinary feature

- php/sync/class-sync-queue.php
Prevent fatal error when there are no assets in the media library
> Math does not allow you to divide by zero

- php/class-plugin.php
Change Video Player version to 3.0.1
- Ensure the Video player works and it doesn't show errors.
> Change Video Player version to 3.0.1

- php/class-plugin.php
Change video player version to 3.0.2
> Change video player version to 3.0.2

- php/class-cron.php
- ui-definitions/settings-pages.php
> Set the cron job feature and cron tasks to off by default
